apiVersion: apps/v1
kind: Deployment
metadata:
  name: sb-demo
  namespace: sb-demo
  labels:
    app: sb-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sb-demo
  template:
    metadata:
      labels:
        app: sb-demo
    spec:
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: sb-demo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
